import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ApiQueryProvider } from "@/lib/api/api-query/Provider";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/store/Providers";
import { SocketProvider } from "@/context/SocketContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <ApiQueryProvider>
          <SocketProvider>
            <Providers>
              {children}
            </Providers>
            <Toaster position="top-center" reverseOrder={false} />
          </SocketProvider>

        </ApiQueryProvider>
      </body>
    </html>
  );
}
